### PR TITLE
#160451489 Add eslint configuration

### PR DESCRIPTION
**Pull request by oladimillion**
#### What does this PR do?
This PR is to add eslint configuration.

#### Description of Task to be completed?
- create a `.eslintrc` file to hold the eslint rules.

#### How should this be manually tested?
- Clone the repo with `git clone -b chore/160451489/configure-eslint https://github.com/andela/phlox-ah.git`
- cd into phlox-ah. `cd phlox-ah`
- run `npm install`
- run `npm run eslint`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
Story type: chore
Story title: Configure ESLint
Story ID: #160451489

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Comment by s-akinrele** [comment]
fix the merge conflict @oladimillion

**Comment by oladimillion** [comment]
> fix the merge conflict @oladimillion

@s-akinrele the conflict is resolved

**Comment by kampkelly** [comment]
LGTM

**Comment by samdiano** [comment]
LGTM

**Pull request merged**
